-- ============================================================
-- BOTM_2.0 - SYSTÈME DE POINTS + BOUTIQUE
-- À exécuter dans Supabase > SQL Editor.
--
-- Cette mise à jour NE SUPPRIME PAS les comptes, collections,
-- decks, boosters ou pioches déjà existants.
--
-- Règles :
--   Booster : 2 000 points, stock illimité.
--   Pioche Miracle : 1 000 points, stock global configurable.
--   Cartes : prix + stock global configurables par l'admin.
-- ============================================================


-- ------------------------------------------------------------
-- 1. POINTS DES JOUEURS
-- ------------------------------------------------------------

alter table public.profiles
add column if not exists points integer not null default 0;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_points_nonnegative'
  ) then
    alter table public.profiles
    add constraint profiles_points_nonnegative
    check (points >= 0);
  end if;
end $$;


-- ------------------------------------------------------------
-- 2. ARTICLES DE BOUTIQUE
-- ------------------------------------------------------------

create table if not exists public.shop_items (
  id bigint generated by default as identity primary key,
  item_type text not null
    check (item_type in ('booster','miracle','card')),
  title text,
  card_id bigint references public.cards(id) on delete cascade,
  price integer not null check (price > 0),
  stock integer,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint shop_item_shape check (
    (
      item_type = 'booster'
      and card_id is null
      and stock is null
    )
    or
    (
      item_type = 'miracle'
      and card_id is null
      and stock is not null
      and stock >= 0
    )
    or
    (
      item_type = 'card'
      and card_id is not null
      and stock is not null
      and stock >= 0
    )
  )
);

create unique index if not exists shop_one_booster
on public.shop_items(item_type)
where item_type = 'booster';

create unique index if not exists shop_one_miracle
on public.shop_items(item_type)
where item_type = 'miracle';

create unique index if not exists shop_one_listing_per_card
on public.shop_items(card_id)
where item_type = 'card';


-- Historique des achats.
create table if not exists public.shop_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint references public.shop_items(id) on delete set null,
  item_type text not null,
  card_id bigint references public.cards(id) on delete set null,
  price_paid integer not null,
  purchased_at timestamptz not null default now()
);

create index if not exists shop_purchases_user_idx
on public.shop_purchases(user_id, purchased_at desc);


-- ------------------------------------------------------------
-- 3. ARTICLES DE BASE
-- ------------------------------------------------------------

insert into public.shop_items(item_type, title, price, stock, active)
select 'booster', 'Booster', 2000, null, true
where not exists (
  select 1 from public.shop_items where item_type = 'booster'
);

insert into public.shop_items(item_type, title, price, stock, active)
select 'miracle', 'Pioche Miracle', 1000, 0, true
where not exists (
  select 1 from public.shop_items where item_type = 'miracle'
);

-- Force les prix demandés pour les deux articles de base.
update public.shop_items
set price = 2000,
    stock = null,
    active = true,
    updated_at = now()
where item_type = 'booster';

update public.shop_items
set price = 1000,
    updated_at = now()
where item_type = 'miracle';


-- ------------------------------------------------------------
-- 4. RLS
-- ------------------------------------------------------------

alter table public.shop_items enable row level security;
alter table public.shop_purchases enable row level security;

revoke all on table public.shop_items, public.shop_purchases
from anon, authenticated;

grant select on public.shop_items to authenticated;
grant select on public.shop_purchases to authenticated;

drop policy if exists "shop items authenticated select" on public.shop_items;
create policy "shop items authenticated select"
on public.shop_items
for select
to authenticated
using (
  active
  or exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
  )
);

drop policy if exists "shop purchases own select" on public.shop_purchases;
create policy "shop purchases own select"
on public.shop_purchases
for select
to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
  )
);


-- ------------------------------------------------------------
-- 5. ADMIN : CRÉDITER DES POINTS
-- ------------------------------------------------------------

create or replace function public.admin_grant_points(
  p_email text,
  p_points integer default 0
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
  target uuid;
begin
  if uid is null
     or not exists (
       select 1
       from public.profiles
       where id = uid and role = 'admin'
     )
  then
    raise exception 'Accès administrateur requis';
  end if;

  if p_points < 0 then
    raise exception 'Valeur de points invalide';
  end if;

  select id
  into target
  from auth.users
  where lower(email) = lower(p_email)
  limit 1;

  if target is null then
    raise exception 'Joueur introuvable';
  end if;

  update public.profiles
  set points = points + p_points
  where id = target;
end;
$$;


-- ------------------------------------------------------------
-- 6. ADMIN : AJOUT / RÉAPPROVISIONNEMENT D'UNE CARTE
-- ------------------------------------------------------------

create or replace function public.admin_shop_upsert_card(
  p_card_id bigint,
  p_price integer,
  p_stock integer
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
  existing_id bigint;
begin
  if uid is null
     or not exists (
       select 1
       from public.profiles
       where id = uid and role = 'admin'
     )
  then
    raise exception 'Accès administrateur requis';
  end if;

  if p_price <= 0 then
    raise exception 'Le prix doit être supérieur à 0';
  end if;

  if p_stock <= 0 then
    raise exception 'Le stock doit être supérieur à 0';
  end if;

  if not exists (
    select 1
    from public.cards
    where id = p_card_id and active
  ) then
    raise exception 'Carte inexistante ou inactive';
  end if;

  select id
  into existing_id
  from public.shop_items
  where item_type = 'card'
    and card_id = p_card_id
  limit 1;

  if existing_id is null then
    insert into public.shop_items(
      item_type, card_id, price, stock, active
    )
    values(
      'card', p_card_id, p_price, p_stock, true
    )
    returning id into existing_id;
  else
    -- Réapprovisionnement : le stock saisi est AJOUTÉ au stock restant.
    update public.shop_items
    set price = p_price,
        stock = stock + p_stock,
        active = true,
        updated_at = now()
    where id = existing_id;
  end if;

  return existing_id;
end;
$$;


-- ------------------------------------------------------------
-- 7. ADMIN : MODIFIER UN ARTICLE
-- ------------------------------------------------------------

create or replace function public.admin_shop_update_item(
  p_item_id bigint,
  p_price integer,
  p_stock integer,
  p_active boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
  kind text;
begin
  if uid is null
     or not exists (
       select 1
       from public.profiles
       where id = uid and role = 'admin'
     )
  then
    raise exception 'Accès administrateur requis';
  end if;

  if p_price <= 0 then
    raise exception 'Prix invalide';
  end if;

  select item_type
  into kind
  from public.shop_items
  where id = p_item_id
  for update;

  if kind is null then
    raise exception 'Article introuvable';
  end if;

  if kind = 'booster' then
    update public.shop_items
    set price = 2000,
        stock = null,
        active = p_active,
        updated_at = now()
    where id = p_item_id;

  else
    if p_stock is null or p_stock < 0 then
      raise exception 'Stock invalide';
    end if;

    update public.shop_items
    set price = case when kind = 'miracle' then 1000 else p_price end,
        stock = p_stock,
        active = p_active,
        updated_at = now()
    where id = p_item_id;
  end if;
end;
$$;


-- ------------------------------------------------------------
-- 8. ACHAT SÉCURISÉ
-- ------------------------------------------------------------

create or replace function public.purchase_shop_item(
  p_item_id bigint
)
returns table(
  item_type text,
  card_id bigint,
  points_remaining integer,
  stock_remaining integer,
  boosters integer,
  miracle_draws integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
  item public.shop_items%rowtype;
  remaining_points integer;
  current_boosters integer;
  current_miracles integer;
begin
  if uid is null then
    raise exception 'Authentification requise';
  end if;

  -- Verrou global sur l'article :
  -- deux joueurs ne peuvent pas acheter le dernier exemplaire simultanément.
  select *
  into item
  from public.shop_items
  where id = p_item_id
    and active
  for update;

  if item.id is null then
    raise exception 'Article indisponible';
  end if;

  -- Verrou du portefeuille du joueur.
  perform 1
  from public.profiles
  where id = uid
  for update;

  if not found then
    raise exception 'Profil joueur introuvable';
  end if;

  if (
    select points
    from public.profiles
    where id = uid
  ) < item.price then
    raise exception 'Points insuffisants';
  end if;

  if item.item_type <> 'booster'
     and coalesce(item.stock, 0) <= 0
  then
    raise exception 'Article épuisé';
  end if;

  -- Retrait des points.
  update public.profiles
  set points = points - item.price
  where id = uid
  returning points, public.profiles.boosters, public.profiles.miracle_draws
  into remaining_points, current_boosters, current_miracles;

  -- Attribution.
  if item.item_type = 'booster' then

    update public.profiles
    set boosters = boosters + 1
    where id = uid
    returning public.profiles.boosters
    into current_boosters;

  elsif item.item_type = 'miracle' then

    update public.shop_items
    set stock = stock - 1,
        updated_at = now()
    where id = item.id;

    update public.profiles
    set miracle_draws = miracle_draws + 1
    where id = uid
    returning public.profiles.miracle_draws
    into current_miracles;

  elsif item.item_type = 'card' then

    update public.shop_items
    set stock = stock - 1,
        updated_at = now()
    where id = item.id;

    perform private.add_user_card(uid, item.card_id);

  else
    raise exception 'Type d''article invalide';
  end if;

  insert into public.shop_purchases(
    user_id,
    item_id,
    item_type,
    card_id,
    price_paid
  )
  values(
    uid,
    item.id,
    item.item_type,
    item.card_id,
    item.price
  );

  return query
  select
    item.item_type,
    item.card_id,
    remaining_points,
    case
      when item.item_type = 'booster' then null
      else (
        select s.stock
        from public.shop_items s
        where s.id = item.id
      )
    end,
    (
      select p.boosters
      from public.profiles p
      where p.id = uid
    ),
    (
      select p.miracle_draws
      from public.profiles p
      where p.id = uid
    );
end;
$$;


-- ------------------------------------------------------------
-- 9. DROITS D'EXÉCUTION
-- ------------------------------------------------------------

revoke execute on function public.admin_grant_points(text,integer)
from public, anon;

revoke execute on function public.admin_shop_upsert_card(bigint,integer,integer)
from public, anon;

revoke execute on function public.admin_shop_update_item(bigint,integer,integer,boolean)
from public, anon;

revoke execute on function public.purchase_shop_item(bigint)
from public, anon;


grant execute on function public.admin_grant_points(text,integer)
to authenticated;

grant execute on function public.admin_shop_upsert_card(bigint,integer,integer)
to authenticated;

grant execute on function public.admin_shop_update_item(bigint,integer,integer,boolean)
to authenticated;

grant execute on function public.purchase_shop_item(bigint)
to authenticated;


-- ------------------------------------------------------------
-- FIN
-- ------------------------------------------------------------
-- Après exécution :
-- 1) Remplace index.html, app.js, admin.html et styles.css sur GitHub.
-- 2) Ajoute boutique.html à la racine de BOTM_2.0.
-- 3) Fais Cmd + Shift + R.
--
-- La Pioche Miracle démarre avec un stock de 0 :
-- ajoute son stock depuis l'Administration avant de la vendre.
